import { Inter } from 'next/font/google'
import './globals.css'
import Button from '@mui/material/Button';
import Link from '@mui/material/Link';



const inter = Inter({ subsets: ['latin'] })



export const metadata = {
  title: 'Film Findr',
  description: 'Generated by the next generation',
}

export default function RootLayout({ children }) {
  return (

   
    <html lang="en">
    <body className={inter.className}>{children}
   
      
    </body>
    </html>
    
)
}
